import React, { useState } from "react";
import { ChevronDown, HelpCircle } from "lucide-react";

const faqs = [
  {
    question: "What is an AI prompt generator?",
    answer: "An AI prompt generator is a tool that helps you create optimized, detailed prompts for AI models like ChatGPT, Midjourney, DALL-E, and Claude. It structures your input to get better, more consistent results from AI systems by applying prompt engineering best practices automatically.",
  },
  {
    question: "Is PromptForge free to use?",
    answer: "Yes, PromptForge is 100% free with no signup required. Generate unlimited AI prompts for any supported model. There are no hidden fees, no credit limits, and no watermarks on your generated prompts.",
  },
  {
    question: "How do I write better ChatGPT prompts?",
    answer: "Great ChatGPT prompts include: 1) A clear role or persona (e.g., 'Act as a senior marketer'), 2) Specific context about your situation, 3) Detailed instructions on what you want, 4) Output format specification (e.g., bullet points, JSON), 5) Examples when possible. PromptForge automates this structure for you automatically.",
  },
  {
    question: "What AI models does PromptForge support?",
    answer: "PromptForge generates optimized prompts for ChatGPT (GPT-4, GPT-4o), Claude (3.5 Sonnet), Midjourney (v6), DALL-E 3, Stable Diffusion (XL, SD3), Google Gemini, and Llama 3. Each model has unique optimization rules — text models get role-based structured prompts, while image models get style descriptors and parameters.",
  },
  {
    question: "Can I use these prompts commercially?",
    answer: "Yes, all prompts generated by PromptForge are yours to use for any purpose including commercial projects. There are no licensing restrictions, no attribution required, and no usage limits. Generate prompts for client work, products, or internal tools freely.",
  },
  {
    question: "How is PromptForge different from a prompt library?",
    answer: "PromptForge is a prompt generator, not just a static library. While we do have 500+ ready-to-use templates, our engine dynamically constructs optimized prompts based on your specific inputs — adapting tone, format, style, and structure for your chosen AI model. It's like having a prompt engineer on demand.",
  },
  {
    question: "Do I need to know prompt engineering to use this?",
    answer: "Not at all! That's the entire point. PromptForge handles the prompt engineering for you. Just describe what you want in plain English, pick your options, and the engine structures it into an optimized prompt. However, if you are a prompt engineer, the advanced settings give you fine-grained control.",
  },
  {
    question: "Will my data be saved or shared?",
    answer: "No. PromptForge runs entirely in your browser. We don't store your prompts, topics, or inputs on any server. There's no account system and no tracking of what you generate. Your prompts are yours alone.",
  },
];

export default function FAQ() {
  const [open, setOpen] = useState(0);

  return (
    <section className="py-24 px-6 bg-[#050505] relative overflow-hidden">
      <div className="max-w-[900px] mx-auto relative z-10">
        <div className="text-center mb-16">
          <div className="inline-flex items-center gap-2 px-4 py-1.5 mb-6 border border-mint/20 bg-mint/5 rounded-full">
            <HelpCircle size={14} className="text-mint" />
            <span className="text-mint text-xs font-bold tracking-[0.15em] uppercase">Got Questions?</span>
          </div>
          <h2 className="text-4xl md:text-6xl font-bold text-mercury mb-4 tracking-tight">
            Frequently Asked <span className="text-gradient-mint">Questions</span>
          </h2>
          <p className="text-ash text-lg max-w-2xl mx-auto">
            Everything you need to know about PromptForge and AI prompt generation.
          </p>
        </div>

        <div className="space-y-3">
          {faqs.map((faq, index) => (
            <div
              key={index}
              className={`bg-carbon border rounded-2xl overflow-hidden transition-all duration-300 ${
                open === index ? "border-mint/20" : "border-white/5"
              }`}
            >
              <button
                onClick={() => setOpen(open === index ? -1 : index)}
                className="w-full flex items-center justify-between p-6 text-left"
              >
                <span className={`font-semibold text-base md:text-lg pr-4 transition-colors ${
                  open === index ? "text-mint" : "text-mercury"
                }`}>
                  {faq.question}
                </span>
                <ChevronDown
                  size={20}
                  className={`flex-shrink-0 transition-transform duration-300 ${
                    open === index ? "rotate-180 text-mint" : "text-obsidian"
                  }`}
                />
              </button>
              <div
                className={`grid transition-all duration-300 ${
                  open === index ? "grid-rows-[1fr] opacity-100" : "grid-rows-[0fr] opacity-0"
                }`}
              >
                <div className="overflow-hidden">
                  <p className="px-6 pb-6 text-ash text-sm md:text-base leading-relaxed">
                    {faq.answer}
                  </p>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}